import '../styles/globals.css'

import { ReactNode } from 'react'

interface IRootLayoutProps {
  children: ReactNode
}

export const metadata = {
  title: 'Next 13 Template',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: IRootLayoutProps) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  )
}
